name: e_commerce
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  easy_localization: ^3.0.3
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_dotenv: ^5.1.0
  flutter_facebook_auth: ^6.0.2
  flutter_form_builder: ^9.1.1
  flutter_slidable: ^3.0.0
  flutter_stripe: ^9.4.0
  flutter_svg: ^2.0.7
  flutter_test:
    sdk: flutter
  fluttertoast: ^8.2.2
  form_builder_validators: ^9.1.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.5
  http: ^1.1.0
  popover: ^0.2.8+2
  provider: ^6.0.5
  syncfusion_flutter_sliders: ^23.1.38

dev_dependencies:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - .env
